# Generated by Django 4.2 on 2023-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
